// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLoSCfoHk8JUhiGBNOysog9RmcCOvlR0',
    appId: '1:445232998608:web:b6fa3ba38c0324750a16d5',
    messagingSenderId: '445232998608',
    projectId: 'agrosafe-47bb2',
    authDomain: 'agrosafe-47bb2.firebaseapp.com',
    storageBucket: 'agrosafe-47bb2.firebasestorage.app',
    measurementId: 'G-B4KB5NN11R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2wxVgor_UDHaRiCezXWHLvCltRavlr4',
    appId: '1:445232998608:android:cb456f49a615e3a20a16d5',
    messagingSenderId: '445232998608',
    projectId: 'agrosafe-47bb2',
    storageBucket: 'agrosafe-47bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRrhe1TbMgKQnggAz9aaB9P32M4SiCoE',
    appId: '1:445232998608:ios:7e195d31502105fe0a16d5',
    messagingSenderId: '445232998608',
    projectId: 'agrosafe-47bb2',
    storageBucket: 'agrosafe-47bb2.firebasestorage.app',
    iosBundleId: 'com.agrosafe.agrosafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRrhe1TbMgKQnggAz9aaB9P32M4SiCoE',
    appId: '1:445232998608:ios:7e195d31502105fe0a16d5',
    messagingSenderId: '445232998608',
    projectId: 'agrosafe-47bb2',
    storageBucket: 'agrosafe-47bb2.firebasestorage.app',
    iosBundleId: 'com.agrosafe.agrosafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLoSCfoHk8JUhiGBNOysog9RmcCOvlR0',
    appId: '1:445232998608:web:8b7558cafe3728420a16d5',
    messagingSenderId: '445232998608',
    projectId: 'agrosafe-47bb2',
    authDomain: 'agrosafe-47bb2.firebaseapp.com',
    storageBucket: 'agrosafe-47bb2.firebasestorage.app',
    measurementId: 'G-LTT1VBYP4Y',
  );
}
